#!/bin/bash

SERVER=admin.mednean.com.ua

echo ''
echo 'Building Back-end...'
echo ''

mvn clean package

echo ''
echo 'Copying app to destination server...'
echo ''
scp -P 2222 ./target/measure-0.0.1-SNAPSHOT.jar bvh@$SERVER:/home/bvh/measure

echo ''
echo 'Enter password for remotely RESTART server'
ssh -tt bvh@$SERVER -p 2222 "sudo systemctl restart measure.service"
