#!/bin/bash

SERVER=185.189.185.80


echo ''
echo 'Building Back-end...'
echo ''
cd ..
mvn clean package

echo ''
echo 'Copying app to destination server...'
echo ''
scp -P 2222 ./target/measure-0.0.1-SNAPSHOT.jar bvh@$SERVER:/home/bvh/mednean_$1

echo ''
echo 'Enter password for remotely RESTART server'
ssh -tt bvh@$SERVER -p 2222 "sudo systemctl stop mednean_$1.service;sudo mv /home/bvh/mednean_$1/elqueue.out /home/bvh/mednean_$1/elqueue.bak;sudo systemctl start mednean_$1.service;exit"
